In [1]:
import numpy as np
print(np.__version__)

1.12.1


In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int64')

In [4]:
a = np.array([1,2,3,4,5,6],dtype=np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.])

In [5]:
a.ndim, a.shape, a.size

(1, (6,), 6)

In [6]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]],dtype=np.float64)

In [7]:
b

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [8]:
b.dtype

dtype('float64')

In [9]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [10]:
np.zeros((3,3), 'd')

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
np.empty((4,4),'d')

array([[  2.31584178e+077,   2.31584178e+077,   7.90505033e-323,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   2.31584178e+077,
          2.31584178e+077]])

In [12]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.random.standard_normal((2,4))

array([[ 1.83390503,  0.05892371, -0.76581157,  0.47339355],
       [-0.72922649, -0.23085658,  0.00627852, -0.41488196]])

In [15]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack((a,b))

array([[-1.99083786, -0.48675146, -1.09553976],
       [ 0.39023008,  0.21062846, -0.132528  ],
       [ 0.42107975, -0.98099296,  1.52200302],
       [ 1.66508414, -0.15756853,  0.23038486]])

In [16]:
np.hstack((a,b))

array([[-1.99083786, -0.48675146, -1.09553976,  0.42107975, -0.98099296,
         1.52200302],
       [ 0.39023008,  0.21062846, -0.132528  ,  1.66508414, -0.15756853,
         0.23038486]])

In [17]:
np.save('example.npy', a)

In [18]:
b = np.load('example.npy')

In [19]:
b

array([[-1.99083786, -0.48675146, -1.09553976],
       [ 0.39023008,  0.21062846, -0.132528  ]])

In [20]:
my_list = [-17, 0, 4, 5, 9]

my_array_from_list = np.array(my_list)

my_array_from_list

array([-17,   0,   4,   5,   9])

In [21]:
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [22]:
my_tuple = (14, -3.54, 5+7j)
np.array(my_tuple)

array([ 14.00+0.j,  -3.54+0.j,   5.00+7.j])

In [23]:
np.array(my_tuple).dtype

dtype('complex128')

###Difference between python and numpy data structures

In [24]:
my_tuple * 6

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [25]:
np.array(my_tuple) * 6

array([ 84.00 +0.j, -21.24 +0.j,  30.00+42.j])

In [26]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])